name: Test Remote Trigger

on:
  repository_dispatch:
    types: [remote_trigger]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.event.client_payload.repo }}
    steps:
      - name: Checkout web repo
        uses: actions/checkout@v3
        with: 
          repository: Faire/${{ github.event.client_payload.repo }}
          # ref: aodan.xin/test-github-action
          token: ${{ secrets.PAT }}
          path: ${{ github.event.client_payload.repo }}

      - name: Set a user
        run: |
          git config --global user.name "Aodan Xin"
          git config --global user.email "aodan.xin@faire.com"

      - name: Change something and push the changes
        env:
          JIRA_Ticket_ID: ${{ github.event.client_payload.jira_ticket_id }}
        run:
          sed -i '/Navigation/i \
            \# $JIRA_Ticket_ID\\\n
            \@Ignore' cypress/integration/testFiles/Analytics.feature

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v4
        with:
          base: aodan.xin/test-github-action
          branch: aodan.xin/test-github-action-pr
          commit-message: "Ignore E2E scenario name"
          title: Test the github action to create a PR
          reviewers: "bryan-holder-faire"
          path: web-brand
          token: ${{ secrets.PAT }}