name: Test Remote Trigger

on:
  repository_dispatch:
    types: [ignore_e2e_pr]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.event.client_payload.repo }}
    steps:
      - name: Checkout web repo
        uses: actions/checkout@v3
        with: 
          repository: Faire/${{ github.event.client_payload.repo }}
          ref: aodan.xin/test-github-action
          token: ${{ secrets.PAT }}
          path: ${{ github.event.client_payload.repo }}

      - name: Set a user
        run: |
          git config --global user.name "Aodan Xin"
          git config --global user.email "aodan.xin@faire.com"

      - name: Change something and push the changes
        run:
          sed -i '/\: ${{ github.event.client_payload.scenario_name }}[ ]*$/i \  \# ${{ github.event.client_payload.jira_ticket_id }}\n  \@Ignore' ${{ github.event.client_payload.file_path }}

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v4
        with:
          base: aodan.xin/test-github-action
          branch: ${{ github.event.client_payload.jira_ticket_id }}/ignore-e2e
          commit-message: Ignore E2E test
          title: Ignore unstable E2E ${{ github.event.client_payload.scenario_name }}
          body: Ignore unstable E2E ${{ github.event.client_payload.scenario_name }}
          reviewers: ${{ github.event.client_payload.reviewer }}
          draft: true
          path: ${{ github.event.client_payload.repo }}
          token: ${{ secrets.PAT }}