name: Test Remote Trigger

on:
  repository_dispatch:
    types: [remote_trigger]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        env:
          JIRA_TICKET_ID: ${{ github.event.client_payload.jira_ticket_id }}
        run: echo Hello, world! $JIRA_TICKET_ID
      
      - name: Checkout web repo
        uses: actions/checkout@v3
        with: 
          repository: Faire/web-brand
          ref: aodan.xin/test-github-action
          token: ${{ secrets.PAT }}
          path: web-brand

      - name: Set a user
        run: |
          git config --global user.name "Aodan Xin"
          git config --global user.email "aodan.xin@faire.com"

      - name: Change something and push the changes
        working-directory: web-brand
        run: |
          echo "This is a test" >> a_new_file
          git add .
          git commit -m "This is a test"
          git push

      - name: Create a pull request
        run: cd web-brand
        uses: repo-sync/pull-request@v2
        with:
          pr_title: Test the github action to create a PR
          pr_reviewer: "bryan-holder-faire"
          github_token: ${{ secrets.PAT }}