name: Test Remote Trigger

on:
  repository_dispatch:
    types: [remote_trigger]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        env:
          JIRA_TICKET_ID: ${{ github.event.client_payload.jira_ticket_id }}
        run: echo Hello, world! $JIRA_TICKET_ID
      
      - name: Checkout web repo
        uses: actions/checkout@v3
        with: 
          repository: Faire/web-brand
          token: ${{ secrets.PAT }}
          path: web-brand

      - name: Change something
        run: |
          cd web-brand
          git checkout aodan.xin/test-github-action
          echo "This is a test" >> a_new_file
          git add .
          git commit -m "This is a test"
          git push
